### ISSUE TITLE
bebbo TOOLCHAIN_PATH question

### ISSUE THREAD

**Issue by simpsond** [AmigaPorts/AmigaCMakeCrossToolchains#17]
The default install path for the bebbo toolchain is `/opt/amiga`. Why doesn't the default TOOLCHAIN_PATH match the default install location?  As it is, anyone that does a default install will always need to specify `-DTOOLCHAIN_PATH=/opt/amiga`

**Comment by xx-shitai-xx** [comment]
Because the toolchain file was created for the docker setup in mind, and it was easier to set up a homogenized multi docker setup for m68k-amigaos, ppc-amigaos and ppc-morphos if all the toolchains used a common format. 

And it makes more sense if you have both ppc-amigaos and m68k-amigaos toolchains installed on your machine as well.
